services:
  - type: web
    name: career-ai
    runtime: docker
    plan: free

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: false

      - key: APP_URL
        value: https://career-ai.onrender.com

      - key: LOG_CHANNEL
        value: stack

      - key: DB_CONNECTION
        value: pgsql

      - key: DB_HOST
        fromDatabase:
          name: career-ai-db
          property: host

      - key: DB_PORT
        fromDatabase:
          name: career-ai-db
          property: port

      - key: DB_DATABASE
        fromDatabase:
          name: career-ai-db
          property: database

      - key: DB_USERNAME
        fromDatabase:
          name: career-ai-db
          property: user

      - key: DB_PASSWORD
        fromDatabase:
          name: career-ai-db
          property: password

databases:
  - name: career-ai-db
    plan: free